version: "3.1"

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    env_file: .env
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672