@baseUrl = http://localhost
@port = 3333
@host = {{baseUrl}}:{{port}}


### Health check
# @name HealthCheck
GET {{host}}/api/healthcheck

### Payment create new bill
# @name PaymentCreateBill
POST {{host}}/api/payment/bill
Content-Type: application/json

{
    "orderId": "{{$guid}}",
    "paymentMethod":{
      "type": "CREDIT_CARD",
      "card": {
        "band": "MASTERCARD",
        "number": "{{$randomInt 1000 9999}}-{{$randomInt 1000 9999}}-{{$randomInt 1000 9999}}-{{$randomInt 1000 9999}}",
        "cvv": "{{$randomInt 100 999}}"
      }
    }
}

### Payment create new bill pix
# @name PaymentCreateBillPix
POST {{host}}/api/payment/bill
Content-Type: application/json

{
    "orderId": "{{$guid}}",
    "paymentMethod":{
      "type": "PIX",
      "pix": {
        "code": "{{$guid}}-{{$randomInt 1000 9999}}"
      }
    }
}

### Payment process bill
# @name PaymentProcessBill
POST {{host}}/api/payment/bill/process

### Payment get bill
# @name PaymentGetBill
GET {{host}}/api/payment/bill/b2182d89-2126-46d8-853c-4f5744a015d1

